# Generated by Django 3.2.12 on 2022-02-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_thumbail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbail',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
