# Generated by Django 3.2.12 on 2022-02-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_thumbail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbail',
            field=models.FileField(upload_to='static/media'),
        ),
    ]
