# Generated by Django 3.2.12 on 2022-02-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_thumbail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='thumbail',
        ),
    ]
