# Generated by Django 3.2.12 on 2022-02-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
